#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HBS.ITAG.Resource", IsApplication=true)]

namespace HBS.ITAG
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060002
			public const int Age = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Gender = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Organization = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int TechFocus = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_features = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blueprintexample = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bluetooth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_scroll_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_spinner = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int house = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ITAG = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int left_arrow = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MyEventsScrollBox = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int navigation_bar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int primaryBox = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int profile = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int right_arrow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ripple_effect = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int secondaryBox = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int selected_day = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tertiaryBox = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int unselected_day = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int whiteBox = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int wrench = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int BluetoothMsg = 2131165186;
			
			// aapt resource value: 0x7f07001d
			public const int DSbutton1 = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int DSedittext = 2131165212;
			
			// aapt resource value: 0x7f070016
			public const int DSrelativeLayout1 = 2131165206;
			
			// aapt resource value: 0x7f070010
			public const int DSrelativeLayout2 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int DSrelativeLayout3 = 2131165203;
			
			// aapt resource value: 0x7f070019
			public const int DSrelativeLayout4 = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int DSspinner1 = 2131165208;
			
			// aapt resource value: 0x7f070012
			public const int DSspinner2 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int DSspinner3 = 2131165205;
			
			// aapt resource value: 0x7f07001b
			public const int DSspinner4 = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int DStextView2 = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int DStextView3 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int DStextView4 = 2131165204;
			
			// aapt resource value: 0x7f07001a
			public const int DStextView5 = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int DStextView7 = 2131165199;
			
			// aapt resource value: 0x7f070020
			public const int EDimageButton1 = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int EDrelativeLayout1 = 2131165214;
			
			// aapt resource value: 0x7f070021
			public const int EDrelativeLayout2 = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int EDrelativeLayout3 = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int EDrelativeLayout4 = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int EDrelativeLayout5 = 2131165226;
			
			// aapt resource value: 0x7f07001f
			public const int EDtextView1 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int EDtextView2 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int EDtextView3 = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int EDtextView4 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int EDtextView5 = 2131165222;
			
			// aapt resource value: 0x7f070028
			public const int EDtextView6 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int EDtextView7 = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int EDtextView8 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int EDtextView9 = 2131165228;
			
			// aapt resource value: 0x7f070008
			public const int Header1 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int Header2 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int Header3 = 2131165197;
			
			// aapt resource value: 0x7f070030
			public const int HomeRelativeLayout1 = 2131165232;
			
			// aapt resource value: 0x7f07000a
			public const int Info1 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int Info2 = 2131165198;
			
			// aapt resource value: 0x7f07003b
			public const int JCTtextView1 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int JCTtextView2 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int JCTtextView3 = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int JCTtextView4 = 2131165246;
			
			// aapt resource value: 0x7f070040
			public const int MElistView1 = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int MElistView2 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int MElistViewTextView1 = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int MElistViewTextView2 = 2131165252;
			
			// aapt resource value: 0x7f07003f
			public const int MEtextView2 = 2131165247;
			
			// aapt resource value: 0x7f070041
			public const int MEtextView6 = 2131165249;
			
			// aapt resource value: 0x7f070006
			public const int Title = 2131165190;
			
			// aapt resource value: 0x7f07002e
			public const int app_features = 2131165230;
			
			// aapt resource value: 0x7f070003
			public const int arrowbutton = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int backhomebutton = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int blueprintexample = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int bluetoothimage = 2131165185;
			
			// aapt resource value: 0x7f070039
			public const int calendar = 2131165241;
			
			// aapt resource value: 0x7f070036
			public const int conference_details = 2131165238;
			
			// aapt resource value: 0x7f07004b
			public const int d1t1left_arrow = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int d1t1right_arrow = 2131165261;
			
			// aapt resource value: 0x7f07004f
			public const int d1t2left_arrow = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int d1t2right_arrow = 2131165264;
			
			// aapt resource value: 0x7f070052
			public const int d1t3left_arrow = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int d1t3right_arrow = 2131165267;
			
			// aapt resource value: 0x7f070056
			public const int d2t1left_arrow = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int d2t1right_arrow = 2131165271;
			
			// aapt resource value: 0x7f070059
			public const int d2t2left_arrow = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int d2t2right_arrow = 2131165274;
			
			// aapt resource value: 0x7f07005c
			public const int d2t3left_arrow = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int d2t3right_arrow = 2131165277;
			
			// aapt resource value: 0x7f070060
			public const int d3t1left_arrow = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int d3t1right_arrow = 2131165281;
			
			// aapt resource value: 0x7f070063
			public const int d3t2left_arrow = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int d3t2right_arrow = 2131165284;
			
			// aapt resource value: 0x7f070066
			public const int d3t3left_arrow = 2131165286;
			
			// aapt resource value: 0x7f070069
			public const int d4t1left_arrow = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int d4t1right_arrow = 2131165290;
			
			// aapt resource value: 0x7f07006c
			public const int d4t2left_arrow = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int d4t2right_arrow = 2131165293;
			
			// aapt resource value: 0x7f07006f
			public const int d4t3left_arrow = 2131165295;
			
			// aapt resource value: 0x7f070067
			public const int day_four = 2131165287;
			
			// aapt resource value: 0x7f070048
			public const int day_four_btn = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int day_one = 2131165257;
			
			// aapt resource value: 0x7f070045
			public const int day_one_btn = 2131165253;
			
			// aapt resource value: 0x7f07005e
			public const int day_three = 2131165278;
			
			// aapt resource value: 0x7f070047
			public const int day_three_btn = 2131165255;
			
			// aapt resource value: 0x7f070054
			public const int day_two = 2131165268;
			
			// aapt resource value: 0x7f070046
			public const int day_two_btn = 2131165254;
			
			// aapt resource value: 0x7f070068
			public const int dayfourTrack1 = 2131165288;
			
			// aapt resource value: 0x7f07006b
			public const int dayfourTrack2 = 2131165291;
			
			// aapt resource value: 0x7f07006e
			public const int dayfourTrack3 = 2131165294;
			
			// aapt resource value: 0x7f07004a
			public const int dayoneTrack1 = 2131165258;
			
			// aapt resource value: 0x7f07004e
			public const int dayoneTrack2 = 2131165262;
			
			// aapt resource value: 0x7f070051
			public const int dayoneTrack3 = 2131165265;
			
			// aapt resource value: 0x7f07005f
			public const int daythreeTrack1 = 2131165279;
			
			// aapt resource value: 0x7f070062
			public const int daythreeTrack2 = 2131165282;
			
			// aapt resource value: 0x7f070065
			public const int daythreeTrack3 = 2131165285;
			
			// aapt resource value: 0x7f070055
			public const int daytwoTrack1 = 2131165269;
			
			// aapt resource value: 0x7f070058
			public const int daytwoTrack2 = 2131165272;
			
			// aapt resource value: 0x7f07005b
			public const int daytwoTrack3 = 2131165275;
			
			// aapt resource value: 0x7f07002f
			public const int favorites_header = 2131165231;
			
			// aapt resource value: 0x7f070032
			public const int first_favorite = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int fourth_favorite = 2131165237;
			
			// aapt resource value: 0x7f070007
			public const int gridLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int gridLayout3 = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int gridLayout5 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int gridLayout7 = 2131165184;
			
			// aapt resource value: 0x7f070038
			public const int house = 2131165240;
			
			// aapt resource value: 0x7f07002d
			public const int itag_icon = 2131165229;
			
			// aapt resource value: 0x7f070037
			public const int linearLayout1 = 2131165239;
			
			// aapt resource value: 0x7f070031
			public const int no_favorites = 2131165233;
			
			// aapt resource value: 0x7f07003a
			public const int profileimage = 2131165242;
			
			// aapt resource value: 0x7f070033
			public const int second_favorite = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int third_favorite = 2131165236;
			
			// aapt resource value: 0x7f07004c
			public const int track_title = 2131165260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppFeatures = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DemographicSurvey = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int JsonCallTester = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyEvents = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MyEventsFavoritesListView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MyEventsPreviousEventsListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Schedule = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000a
			public const int ApplicationName = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Info1 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Info2 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int conferenceDetails = 2130968590;
			
			// aapt resource value: 0x7f040000
			public const int error_no_bluetooth_enabled = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int error_no_bluetooth_le = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_no_location_permission = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int requesting_location_access = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int requesting_location_access_cancel = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int requesting_location_access_ok = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int requesting_location_access_rationale = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int requesting_location_permission = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int requesting_location_permission_rationale = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int surveyDescription = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Transparent = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
