#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HBS.ITAG.Resource", IsApplication=true)]

namespace HBS.ITAG
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int Age = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Gender = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int States = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_features = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blueprintexample = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bluetooth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int house = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int inProgress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ITAG = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int profile = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Upcoming = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wrench = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int BluetoothMsg = 2131099650;
			
			// aapt resource value: 0x7f06001e
			public const int DSbutton1 = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int DScheckBox1 = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int DSedittext = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int DSedittext2 = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int DSrelativeLayout1 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int DSrelativeLayout2 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int DSrelativeLayout3 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int DSrelativeLayout4 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int DSrelativeLayout5 = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int DSspinner1 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int DSspinner2 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int DSspinner3 = 2131099670;
			
			// aapt resource value: 0x7f06000f
			public const int DStextView2 = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int DStextView3 = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int DStextView4 = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int DStextView5 = 2131099673;
			
			// aapt resource value: 0x7f06001c
			public const int DStextView6 = 2131099676;
			
			// aapt resource value: 0x7f06000d
			public const int DStextView7 = 2131099661;
			
			// aapt resource value: 0x7f060021
			public const int EDimageButton1 = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int EDrelativeLayout1 = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int EDrelativeLayout2 = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int EDrelativeLayout3 = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int EDrelativeLayout4 = 2131099688;
			
			// aapt resource value: 0x7f06002b
			public const int EDrelativeLayout5 = 2131099691;
			
			// aapt resource value: 0x7f060020
			public const int EDtextView1 = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int EDtextView2 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int EDtextView3 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int EDtextView4 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int EDtextView5 = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int EDtextView6 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int EDtextView7 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int EDtextView8 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int EDtextView9 = 2131099693;
			
			// aapt resource value: 0x7f060006
			public const int Header1 = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int Header2 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int Header3 = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int Info1 = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int Info2 = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int Title = 2131099652;
			
			// aapt resource value: 0x7f06002f
			public const int app_features = 2131099695;
			
			// aapt resource value: 0x7f06000a
			public const int blueprintexample = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int bluetoothimage = 2131099649;
			
			// aapt resource value: 0x7f060039
			public const int conference_details = 2131099705;
			
			// aapt resource value: 0x7f060030
			public const int favorites_header = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int first_favorite = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int first_status = 2131099698;
			
			// aapt resource value: 0x7f060037
			public const int fourth_favorite = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int fourth_status = 2131099704;
			
			// aapt resource value: 0x7f060005
			public const int gridLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int gridLayout3 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int gridLayout5 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int gridLayout7 = 2131099648;
			
			// aapt resource value: 0x7f06002e
			public const int itag_icon = 2131099694;
			
			// aapt resource value: 0x7f060033
			public const int second_favorite = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int second_status = 2131099700;
			
			// aapt resource value: 0x7f06003d
			public const int tempToEventDetails = 2131099709;
			
			// aapt resource value: 0x7f06003b
			public const int tempToMyEvents = 2131099707;
			
			// aapt resource value: 0x7f06003a
			public const int tempToSchedule = 2131099706;
			
			// aapt resource value: 0x7f06003c
			public const int textView1 = 2131099708;
			
			// aapt resource value: 0x7f06003e
			public const int textView2 = 2131099710;
			
			// aapt resource value: 0x7f060035
			public const int third_favorite = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int third_status = 2131099702;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppFeatures = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DemographicSurvey = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyEvents = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Schedule = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Info1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Info2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int conferenceDetails = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int surveyDescription = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
